# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class WiFiListInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, mac_address: str=None, strength: str=None, snr: str=None, channel: str=None):  # noqa: E501
        """WiFiListInner - a model defined in Swagger

        :param mac_address: The mac_address of this WiFiListInner.  # noqa: E501
        :type mac_address: str
        :param strength: The strength of this WiFiListInner.  # noqa: E501
        :type strength: str
        :param snr: The snr of this WiFiListInner.  # noqa: E501
        :type snr: str
        :param channel: The channel of this WiFiListInner.  # noqa: E501
        :type channel: str
        """
        self.swagger_types = {
            'mac_address': str,
            'strength': str,
            'snr': str,
            'channel': str
        }

        self.attribute_map = {
            'mac_address': 'macAddress',
            'strength': 'strength',
            'snr': 'SNR',
            'channel': 'channel'
        }
        self._mac_address = mac_address
        self._strength = strength
        self._snr = snr
        self._channel = channel

    @classmethod
    def from_dict(cls, dikt) -> 'WiFiListInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WiFiList_inner of this WiFiListInner.  # noqa: E501
        :rtype: WiFiListInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mac_address(self) -> str:
        """Gets the mac_address of this WiFiListInner.


        :return: The mac_address of this WiFiListInner.
        :rtype: str
        """
        return self._mac_address

    @mac_address.setter
    def mac_address(self, mac_address: str):
        """Sets the mac_address of this WiFiListInner.


        :param mac_address: The mac_address of this WiFiListInner.
        :type mac_address: str
        """

        self._mac_address = mac_address

    @property
    def strength(self) -> str:
        """Gets the strength of this WiFiListInner.


        :return: The strength of this WiFiListInner.
        :rtype: str
        """
        return self._strength

    @strength.setter
    def strength(self, strength: str):
        """Sets the strength of this WiFiListInner.


        :param strength: The strength of this WiFiListInner.
        :type strength: str
        """

        self._strength = strength

    @property
    def snr(self) -> str:
        """Gets the snr of this WiFiListInner.


        :return: The snr of this WiFiListInner.
        :rtype: str
        """
        return self._snr

    @snr.setter
    def snr(self, snr: str):
        """Sets the snr of this WiFiListInner.


        :param snr: The snr of this WiFiListInner.
        :type snr: str
        """

        self._snr = snr

    @property
    def channel(self) -> str:
        """Gets the channel of this WiFiListInner.


        :return: The channel of this WiFiListInner.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this WiFiListInner.


        :param channel: The channel of this WiFiListInner.
        :type channel: str
        """

        self._channel = channel
